on:
  issues:
    types: [opened]

jobs:
  create_task:
    runs-on: ubuntu-latest
    name: Create a Todoist task
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Todoist Step
        uses: ./
        id: todoist
        with:
          token: ${{ secrets.TODOIST_API_KEY }}
          project-name: Inbox
